### ISSUE TITLE
Sometimes (0) is not detected correctly

### ISSUE THREAD

**Issue by rickpastoor** [rickpastoor/scrummer#7]

**Comment by koenbollen** [comment]
I've got an example here:
<img width="153" alt="screen_shot_2015-09-07_at_17 35 07" src="https://cloud.githubusercontent.com/assets/213502/9720942/b9b5ba74-5593-11e5-8835-24a024d1dac2.png">

**Comment by rickpastoor** [comment]
Fixed!
